@baseUrl = http://localhost:4000/api/v1

###
GET {{baseUrl}}/


###
POST {{baseUrl}}/login
Content-Type: application/json

{
   //"email" : "mad@mad.com",
   "username" : "madness",
    "password" : "madness"
}


###
POST {{baseUrl}}/signin
Content-Type: application/json

{
   "username" : "madness",
   "email" : "mad@mad.com",
   "dateOfBirth" : "1995-11-14",
   "password" : "madness"
}